// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAODg6v0v75AUXDBrlHf3QF_9WFOfOb31o',
    appId: '1:570150660672:web:c1decf25550034b4250da5',
    messagingSenderId: '570150660672',
    projectId: 'blogapp-9a39e',
    authDomain: 'blogapp-9a39e.firebaseapp.com',
    storageBucket: 'blogapp-9a39e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLU4CinFJuJAwgqBDIf6lH-fd7-HIhw0Y',
    appId: '1:570150660672:android:f3bc3aba0f86db5b250da5',
    messagingSenderId: '570150660672',
    projectId: 'blogapp-9a39e',
    storageBucket: 'blogapp-9a39e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYr1foH04nxjkxRJPlLsJEvL6Q4EVRpE',
    appId: '1:570150660672:ios:e8c76924056c20bc250da5',
    messagingSenderId: '570150660672',
    projectId: 'blogapp-9a39e',
    storageBucket: 'blogapp-9a39e.appspot.com',
    androidClientId: '570150660672-pgnsos0rd3307fglgdlnal4r85jgof2l.apps.googleusercontent.com',
    iosClientId: '570150660672-r09qe97v623bfkhu655999816l6b0245.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtYr1foH04nxjkxRJPlLsJEvL6Q4EVRpE',
    appId: '1:570150660672:ios:e8c76924056c20bc250da5',
    messagingSenderId: '570150660672',
    projectId: 'blogapp-9a39e',
    storageBucket: 'blogapp-9a39e.appspot.com',
    androidClientId: '570150660672-pgnsos0rd3307fglgdlnal4r85jgof2l.apps.googleusercontent.com',
    iosClientId: '570150660672-r09qe97v623bfkhu655999816l6b0245.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAODg6v0v75AUXDBrlHf3QF_9WFOfOb31o',
    appId: '1:570150660672:web:14c656d0e755d86a250da5',
    messagingSenderId: '570150660672',
    projectId: 'blogapp-9a39e',
    authDomain: 'blogapp-9a39e.firebaseapp.com',
    storageBucket: 'blogapp-9a39e.appspot.com',
  );

}